[package]
name = "fs-dkr"
version = "0.1.0"
authors = [
    "Omer Shlomovits <omer.shlomovits@gmail.com>",
    "Tudor Cebere <tudorcebere@gmail.com>",
    "Drew Stone <drew@webb.tools>",
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.paillier]
version = "0.4.2"
package = "kzen-paillier"
default-features = false

[dependencies.multi-party-ecdsa]
# git = "https://github.com/webb-tools/multi-party-ecdsa"
path = "../multi-party-ecdsa"
default-features = false

[dependencies]
zk-paillier = { version = "0.4.3", default-features = false }
curv = { package = "curv-kzen", version = "0.9", default-features = true }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
zeroize = "1"
round-based = { version = "0.1.4", features = ["dev"] }
thiserror = "1.0.26"
sha2 = "0.9"